// src/content/React-CSharp/ClientApp/src/components/FetchData.js
import React from 'react';
import { useState, useEffect } from 'react';
////#if (IndividualLocalAuth)
import authService from './api-authorization/AuthorizeService'
////#endif

export function FetchData() {
  const [forecasts, setForecasts] = useState([]);
  const [loading, setLoading] = useState(true);
  
  useEffect(() => {
    populateWeatherData();
  }, [])
  
  const populateWeatherData = async () => {
    ////#if (IndividualLocalAuth)
    const token = await authService.getAccessToken();
    const response = await fetch('weatherforecast', {
      headers: !token ? {} : {'Authorization': `Bearer ${token}`}
    });
    ////#else
    const response = await fetch('weatherforecast');
    ////#endif
    const data = await response.json();
    setForecasts(data);
    setLoading(false);
  };

  const renderForecastsTable = (forecasts) => {
    return (
      <table className='table table-striped' aria-labelledby="tableLabel">
        <thead>
        <tr>
          <th>Date</th>
          <th>Temp. (C)</th>
          <th>Temp. (F)</th>
          <th>Summary</th>
        </tr>
        </thead>
        <tbody>
        {forecasts.map(forecast =>
          <tr key={forecast.date}>
            <td>{forecast.date}</td>
            <td>{forecast.temperatureC}</td>
            <td>{forecast.temperatureF}</td>
            <td>{forecast.summary}</td>
          </tr>
        )}
        </tbody>
      </table>
    );
  }

  let contents = loading
      ? <p><em>Loading...</em></p>
      : renderForecastsTable(forecasts);

  return (
    <div>
      <h1 id="tableLabel">Weather forecast</h1>
      <p>This component demonstrates fetching data from the server.</p>
      {contents}
    </div>
  );
}

// src/content/Angular-CSharp/ClientApp/src/app/fetch-data/fetch-data.component.ts
import { Component, Inject } from '@angular/core';

@Component({
  selector: 'app-fetch-data',
  templateUrl: './fetch-data.component.html'
})
export class FetchDataComponent {
  public forecasts: WeatherForecast[] = [];

  constructor(@Inject('BASE_URL') baseUrl: string) {
    fetch(baseUrl + 'weatherforecast').then(response => {
////#if (IndividualLocalAuth)
      if (response.redirected && response.url.startsWith(`${baseUrl}Identity/Account/Login`)) {
        window.location.href = `${baseUrl}Identity/Account/Login?ReturnUrl=/fetch-data`;
      }
////#endif
      return response.json();
    }).then(result => {
      this.forecasts = result;
    }, error => console.error(error));
  }
}

interface WeatherForecast {
  date: string;
  temperatureC: number;
  temperatureF: number;
  summary: string;
}

<h1 id="tableLabel">Weather forecast</h1>

<p>This component demonstrates fetching data from the server.</p>

<p *ngIf="!forecasts?.length"><em>Loading...</em></p>

<table class='table table-striped' aria-labelledby="tableLabel" *ngIf="forecasts.length">
  <thead>
    <tr>
      <th>Date</th>
      <th>Temp. (C)</th>
      <th>Temp. (F)</th>
      <th>Summary</th>
    </tr>
  </thead>
  <tbody>
    <tr *ngFor="let forecast of forecasts">
      <td>{{ forecast.date | date :'medium' }}</td>
      <td>{{ forecast.temperatureC }}</td>
      <td>{{ forecast.temperatureF }}</td>
      <td>{{ forecast.summary }}</td>
    </tr>
  </tbody>
</table>
